### ISSUE TITLE
multithreading issue

### ISSUE THREAD

**Issue by laurentcau** [vpetrigo/caches#24]
Hi,

I think there is a conception design issue in the thread safe part. 
Even internal code methods are protected by mutex, the API doesn't look to be threadsafe:
Indeed, TryGet return an iterator that can be invalidate by concurrent Put.
The same with Get that return a const reference, you can't guaranty the reference is still valid outside the Get method.

Regards,
Laurent

**Comment by vpetrigo** [comment]
Hello @laurentcau,

What you describes relates to "transaction" thread-safety rather than object thread-safety. Indeed, a reference/pointer returned by `Get`/`TryGet` methods may be invalidated by calls to `Put`/`Remove`. But it is up to a caller to provide a safety of a cache container in a multithreading environment. Or a method might be introduced that would return a shared pointer to a data to avoid early resource invalidation.

I would be more than happy to merge such a change if you see a value for doing so. 😄

**Comment by laurentcau** [comment]
Hi Vladimir,

“But it is up to a caller to provide a safety of a cache container in a multithreading environment.”
That’s what I think too.
The internal mutex makes user wrongly think the container usage is thread-safe and you can use it without extra synchronization code.
If you have to manage thread-safety on caller side, this mutex is useless.
As I know, standard library (stl) doesn’t provide thread-safe container and that’s fine.
I think you should remove all synchronization primitives and just inform that the container is not thread safe in the documentation.

Regards,
Laurent

**Comment by vpetrigo** [comment]
Missed a response there. 🤦
> If you have to manage thread-safety on caller side, this mutex is useless.
No, it is not as `Put`/`Get` operation is not atomic, thus we cannot have thread-safety without locking underlying containers.
Regarding what you described - it is fully application specific. If you have separate threads - one for getting and processing data in cache and another one for putting data into a cache, you are responsible for locking producer-consumer to avoid freed data manipulation.

Since it is quite old thread, I'll close it, but feel free to re-open it, if you have an example that shows why we need to update the existing interface to get rid of references.
