### ISSUE TITLE
是否支持时间过期？

### ISSUE THREAD

**Issue by bayueqiankong** [vpetrigo/caches#30]
设置每个item的时间，如果时间到了，cache中的的item失效丢弃，即超时过期清除

**Comment by vpetrigo** [comment]
Hey @bayueqiankong,

Would you update your question in English please? If I understood translation correctly, you requested a TTL cache implementation. That policy can be implemented, but it requires slightly different interface than `caches` library has right now, since you need a method to call periodically to delete expired items from cache.

**Comment by vpetrigo** [comment]
Feel free to reopen this issue if you come up with other questions/proposals. 😄
